language: cpp
compiler: gcc
sudo: required

# Start virtual X server
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
 - ./build_test.sh
 - ./travis_qmake_gcc_cpp98_qt_qtests_test
 - ./build_normal.sh

 